# Generated by Django 4.2.11 on 2024-05-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='Name',
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.FloatField(max_length=150),
        ),
    ]
