# Generated by Django 4.2.11 on 2024-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_catagory_name_alter_product_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='Name',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
